package com.seedit.diet.database

import android.arch.persistence.db.SupportSQLiteDatabase
import android.arch.persistence.room.Database
import android.arch.persistence.room.Room
import android.arch.persistence.room.RoomDatabase
import android.arch.persistence.room.TypeConverters
import android.content.Context
import com.gondev.clog.CLog
import com.seedit.diet.R
import com.seedit.diet.database.converter.DateConverter
import com.seedit.diet.database.converter.DietCategoryConverter
import com.seedit.diet.database.converter.UriConverter
import com.seedit.diet.database.dao.*
import com.seedit.diet.database.entity.*
import com.seedit.diet.util.ioThread
import java.util.*

@TypeConverters(DateConverter::class,
		UriConverter::class,
		DietCategoryConverter::class)
@Database(entities = [ProfileEntity::class,
						RecommendDietEntity::class,
						DietEntity::class,
						RecommendDietRelationshipEntity::class,
						FoodEntity::class,
						DietFoodRelationEntity::class,
						RecommendWorkoutEntity::class,
						RecommendWorkoutRelationshipEntity::class,
						WorkoutEntity::class,
						WorkoutRelationshipEntity::class],
		version = 1)
abstract class AppDatabase : RoomDatabase()
{
    abstract fun profileDao(): ProfileDao
    abstract fun recommendDietDao(): RecommendDietDao
    abstract fun dietDao(): DietDao
	abstract fun recommendDietRelationshipDao(): RecommendDietRelationshipDao
	abstract fun foodDao():FoodDao
	abstract fun dietFoodDao():DietFoodRelationDao
	abstract fun recommendWorkoutDao(): RecommendWorkoutDao
	abstract fun recommendWorkoutRelationshipDao(): RecommendWorkoutRelationshipDao
	abstract fun workoutDao(): WorkoutDao
	abstract fun workoutRelationship(): WorkoutRelationshipDao

	companion object
    {
        @Volatile private var INSTANCE: AppDatabase? = null

        fun getInstance(context: Context): AppDatabase =
                INSTANCE ?: synchronized(this) {
                    INSTANCE ?: buildDatabase(context).also { INSTANCE = it }
                }

        private fun buildDatabase(context: Context) =
                Room.databaseBuilder(context.applicationContext,
                        AppDatabase::class.java, "com.seedit.diet.db")
                        .addCallback(object : RoomDatabase.Callback()
                        {
                            override fun onCreate(db: SupportSQLiteDatabase) {
                                super.onCreate(db)
                                //TODO 초기 디비 값 설정
                                CLog.i("디비 생성")
                                ioThread {
                                    val calendar= Calendar.getInstance()
                                    calendar.add(Calendar.DATE,-1)

                                    AppDatabase.getInstance(context.applicationContext).apply {
                                        runInTransaction{
                                            recommendDietDao().insertAll(getRecommendDietList())
	                                        recommendWorkoutDao().insertAll(getRecommendWorkoutList())
	                                        foodDao().insertAll(getFoodList())
                                        }
                                    }
                                }
                            }
                        })
                        .build()

	    fun getRecommendDietList()=arrayOf(
                RecommendDietEntity(R.drawable.recommend1,"오트밀 20g, 바나나 100g, 사과 125g, 우유 200ml",345),
                RecommendDietEntity(R.drawable.recommend2,"현미밥 70g, 미역국 300g, 배추김치 50g, 가자미구이 50g",207),
                RecommendDietEntity(R.drawable.recommend3,"삶은 달걀 100g, 찐 고구마 200g, 닭가슴살 샐러드 100g",448)
        )

	    private fun getRecommendWorkoutList()=arrayOf(
			    RecommendWorkoutEntity("abcd","seaf",382f,R.drawable.workout1),
			    RecommendWorkoutEntity("asdf","saef",382f,R.drawable.workout1),
			    RecommendWorkoutEntity("qwer","saef",382f,R.drawable.workout1),

			    RecommendWorkoutEntity("걷기","운동으로서의 걷기는 자연스럽고 편안하게 하되, 천천히 걷기부터 시작하여 경쾌하면서도 약간 빠르게 해야 효과가 있다.\\n 약간 빠르게 30분120칼로리",120f,R.drawable.workout1),
			    RecommendWorkoutEntity("달리기 (조깅)","조깅은 일반적으로 시속 8km 정도의 속도로 달리는 것을 말한다. 운동 초기에는 운동시간을 짧게 하고, 점차적으로 거리와 시간을 늘리면서 걷기와 조깅을 번갈아 실시해야 한다.\n가볍게 30분 189Kcal",189f,R.drawable.workout2),
			    RecommendWorkoutEntity("계단 오르기 (걷기)","배에 힘을 주어 허리를 곧게 편 상태를 유지한다.\n가볍게 30분 189Kcal",189f,R.drawable.workout3),
			    RecommendWorkoutEntity("계단 오르기 (뛰기)","가볍게 조깅하듯이 계단을 뛰어 올라갔다 내려온다. 내려 오는 동작에서 방심하지 말고 끝까지 집중하여 운동한다.\n가볍게 30분 252Kcal",252f,R.drawable.workout4),
			    RecommendWorkoutEntity("런닝머신 걷기","런닝머신은 천천히 걷기, 조깅 달리기 등 자신의 체력수준에 따라 속도를 임의로 조정할 수 있기 때문에 페이스나 기술향상은 물론, 설정된 목표에 알맞게 가장 안전하고 편안하게 운동할 수 있다.\n4.0km/h 30분 92Kcal",92f,R.drawable.workout5),
			    RecommendWorkoutEntity("런닝머신 뛰기","런닝머신은 천천히 걷기, 조깅 달리기 등 자신의 체력수준에 따라 속도를 임의로 조정할 수 있기 때문에 페이스나 기술향상은 물론, 설정된 목표에 알맞게 가장 안전하고 편안하게 운동할 수 있다.\n5.5km/h 30분 197Kcal",197F,R.drawable.workout5),
			    RecommendWorkoutEntity("줄넘기","양발로 밟고 섰을 때 자신의 허리와 가슴 사이까지 올 정도의 길이로 줄넘기를 맞춘다. 허리를 곧게 편 상태를 유지하며 가볍게 두 발을 모아 줄을 넘는다.\n빠르게 30분 378Kcal",378f,R.drawable.workout7),
			    RecommendWorkoutEntity("스피닝","칼로리 소모가 큰 고강도 운동으로, 바른자세로 운동하지 않으면 허리와 무릎 등에 부상을 입을 수 있다. 페달링에 익숙해지면 페달의 저항력이나 케이던스를 높여 운동 강도를 조절할 수 있다.\n보통으로 30분 252Kcal",252f,R.drawable.workout8),
			    RecommendWorkoutEntity("데드리프트","둔근, 대퇴 후면 근육 등 전신 근육 발달에 중요한 영향을 끼치는 운동이다. 신체의 파워를 기를 수 있고, 몸통을 둘러싸고 있는 근육들의 근력을 전반적으로 향상시킬 수 있는 운동이다.\n보통으로 30분 252Kcal",252f,R.drawable.workout10),
			    RecommendWorkoutEntity("벤치 프레스 - 디클라인","대흉근의 아랫부분을 발달시켜 보다 완성도 높은 대흉근의 모양을 만들어준다. 벤치의 각도는 30~45도가 적당하다.\n보통으로 30분 252Kcal",252f,R.drawable.workout11),
			    RecommendWorkoutEntity("벤치 프레스 - 인클라인","동작의 가동 범위를 최대화시켜 대흉근을 발달시키는 운동이다. 수축과 이완 시 덤벨의 균형을 잘 잡아야 하므로 균형감각을 키울 수 있다.\n보통으로 30분 221Kcal",252f,R.drawable.workout12),
			    RecommendWorkoutEntity("레그 컬 - 라잉","대퇴후면의 슬굴곡근을 발달시키기 위한 운동이다. 스탠딩 레그 컬보다 많은 중량을 들 수 있는 것이 장점으로, 하체 근력이 약한 사람에게 필수적인 운동이다.\n보통으로 30분 221Kcal",221f,R.drawable.workout13),
			    RecommendWorkoutEntity("런지","대표적인 다리 운동 중 하나로 허벅지와 엉덩이에 탄력을 주며 하체 근력을 강화하는 운동이다. 더 강한 운동 효과를 원한다면 덤벨이나 바벨을 이용하여 천천히 운동하는 것이 좋다.\n보통으로 30분 249Kcal",249f,R.drawable.workout14),
			    RecommendWorkoutEntity("랫 풀 다운 - 머신","광배근을 발달시키기 위한 대표적인 운동이다. 턱걸이를 하기 어려운 초보자들에게 좋은 운동이다.\n보통으로 30분 252Kcal",252f,R.drawable.workout15),
			    RecommendWorkoutEntity("레그 레이즈","하복부를 단련하는 대표적인 운동이다. 다리를 들어올리는 근육의 힘을 이용하여 동작하는 운동이다.\n보통으로 30분 221Kcal",221f,R.drawable.workout16),
			    RecommendWorkoutEntity("레그 익스텐션","허벅지 전면 근육을 발달시키는 운동이다. 두 다리의 근력 수준 차이를 극복하기 위해 한 발씩 실시해도 좋은 운동이다.\n보통으로 30분 221Kcal",221f,R.drawable.workout17),
			    RecommendWorkoutEntity("레그 프레스","대퇴사두근과 둔근을 강화시켜주는 대표적이고 필수적인 하체 운동이다. 스쿼트에 비해 허리에 가해지는 부하가 적어 비교적 무거운 무게로 운동할 수 있는 장점이 있다.\n보통으로 30분 252Kcal",252f,R.drawable.workout18),
			    RecommendWorkoutEntity("푸시업 (팔굽혀펴기)","가장 널리 알려진 대흉근 운동이다. 안전하고 효과적으로 상체를 단련할 수 있는 운동으로 의자나 상자 위에 다리를 올려놓고 실시하면 대흉근 발달에 더욱 효과적이다.\n보통으로 30분 221Kcal",221f,R.drawable.workout19),
			    RecommendWorkoutEntity("스쿼트","다리 근력 향상에 효과적인 운동으로 알려졌지만 실제로는 여러 근육을 자극하므로 전신운동에 가깝다. 하체 운동 중에서도 에너지 소모가 높아 체지방 감소에도 효과적이다. \n보통으로 30분 252Kcal",252f,R.drawable.workout20),
			    RecommendWorkoutEntity("윗몸일으키키","가장 일반적으로 할 수 있는 복근 운동이다. 앉았다 누웠다를 반복하는 동작이므로 복근과 다리를 들어올리는 근육을 발달시킬 수 있다.\n보통으로 30분 189Kcal",189f,R.drawable.workout21),
			    RecommendWorkoutEntity("컬 덤벨","상완이두근의 선명도를 높일 수 있는 운동이다. 선 자세와 앉은 자세(벤치, 짐볼)에서 운동이 가능하며, 그립을 잡는 방향에 따라 발현되는 근육이 달라진다.\n보통으로 30분 252Kcal",252f,R.drawable.workout22),
			    RecommendWorkoutEntity("고정 자전거 (사이클 에르고미터)","속도와 저항을 조절하여 운동량을 결정할 수 있기 때문에 실외에서 타는 경우와 비교할 때보다 정확한 양으로 운동하기 좋다.\n보통으로 30분 221Kcal",221f,R.drawable.workout24),
			    RecommendWorkoutEntity("수영","스포츠 종전신 운동으로 큰 호흡운동을 요구하기 때문에 근육이나 심폐의 발달에 좋다.\n접영 30분 347Kcal",347f,R.drawable.workout25),
			    RecommendWorkoutEntity("자전거","자전거 운동은 발목이나 무릎에 부담을 주지 않으면서 칼로리 소비를 많이 할 수 있는 효과적인 운동이다.\n 달리기, 걷기 운동에 비하여 하체에 의존하는 비율이 높기 때문에 운동 지속시간을 길게 할 필요가 있다. \n가볍게 30분 189Kcal",189f,R.drawable.workout23)
			    )

	    fun getFoodList()= arrayOf(
			    FoodEntity("abcd",382f),
			    FoodEntity("asdf",382f),
			    FoodEntity("qwer",382f),

			    FoodEntity("오트밀",382f),
			    FoodEntity("녹두 가공(면류), 녹두국수 ",345f),
			    FoodEntity("대두 가공(과자류), 엿강정 ",135.3f),
			    FoodEntity("들깨 가공(과자류), 엿강정 ",161.4f),
			    FoodEntity("땅콩 가공(과자류), 엿강정 ",173.4f),
			    FoodEntity("라면,봉지면, 진라면, 매운맛(오뚜기)",421f),
			    FoodEntity("멥쌀 가공(과자류), 쌀과자 ",474f),
			    FoodEntity("멥쌀 가공(과자류), 쌀엿강정 ",383f),
			    FoodEntity("멥쌀 가공(과자류), 튀김쌀과자 ",139.5f),
			    FoodEntity("멥쌀 가공(과자류), 튀밥 ",406f),
			    FoodEntity("멥쌀 가공(떡류), 가래떡 ",217f),
			    FoodEntity("멥쌀 가공(떡류), 가래떡, 흑미가래떡 ",209f),
			    FoodEntity("멥쌀 가공(떡류), 개피떡 ",207f),
			    FoodEntity("멥쌀 가공(떡류), 개피떡, 쑥개피떡 ",208f),
			    FoodEntity("멥쌀 가공(떡류), 꿀떡 ",215f),
			    FoodEntity("멥쌀 가공(떡류), 무지개떡 ",229f),
			    FoodEntity("멥쌀 가공(떡류), 백설기 ",234f),
			    FoodEntity("멥쌀 가공(떡류), 송편, 검정콩 ",200f),
			    FoodEntity("멥쌀 가공(떡류), 송편, 깨 ",224f),
			    FoodEntity("멥쌀 가공(떡류), 송편, 팥 ",200f),
			    FoodEntity("멥쌀 가공(떡류), 시루떡 ",217f),
			    FoodEntity("멥쌀 가공(떡류), 쑥설기 ",242f),
			    FoodEntity("멥쌀 가공(떡류), 절편 ",220f),
			    FoodEntity("멥쌀 가공(떡류), 증편 ",177f),
			    FoodEntity("멥쌀 가공(밥죽류), 누룽지",393f),
			    FoodEntity("멥쌀 가공(밥죽류), 백미, 미음 ",21f),
			    FoodEntity("멥쌀 가공(밥죽류), 백미, 밥 ",152f),
			    FoodEntity("멥쌀 가공(밥죽류), 백미, 죽 ",71f),
			    FoodEntity("멥쌀 가공(밥죽류), 현미, 미음 ",20f),
			    FoodEntity("멥쌀 가공(밥죽류), 현미, 밥 ",167f),
			    FoodEntity("멥쌀 가공(밥죽류), 현미, 죽 ",70f),
			    FoodEntity("밀 가공(과자류), 건빵 ",415f),
			    FoodEntity("밀 가공(과자류), 만주, 밤 ",309f),
			    FoodEntity("밀 가공(과자류), 모나카 ",335f),
			    FoodEntity("밀 가공(과자류), 센베이 ",398f),
			    FoodEntity("밀 가공(과자류), 센베이, 김 ",423f),
			    FoodEntity("밀 가공(과자류), 스넥, 감자 ",540f),
			    FoodEntity("밀 가공(과자류), 스넥, 새우 ",537f),
			    FoodEntity("밀 가공(과자류), 스넥, 옥수수 ",526f),
			    FoodEntity("밀 가공(과자류), 약과 ",422f),
			    FoodEntity("밀 가공(과자류), 웨하스, 바닐라 ",521f),
			    FoodEntity("밀 가공(과자류), 초코볼 ",501f),
			    FoodEntity("밀 가공(과자류), 초코파이 ",441f),
			    FoodEntity("밀 가공(과자류), 쿠키, 땅콩버터 ",476f),
			    FoodEntity("밀 가공(과자류), 쿠키, 버터 ",467f),
			    FoodEntity("밀 가공(과자류), 쿠키, 초코칩 ",526f),
			    FoodEntity("밀 가공(과자류), 크랙커 ",513f),
			    FoodEntity("밀 가공(과자류), 크랙커, 땅콩샌드 ",496f),
			    FoodEntity("밀 가공(과자류), 크랙커, 치즈샌드 ",490f),
			    FoodEntity("밀 가공(과자류), 피칸파이 ",345f),
			    FoodEntity("밀 가공(면류), 중국국수, 증숙면",198f),
			    FoodEntity("밀 가공(빵류), 건포도빵",269f),
			    FoodEntity("밀 가공(빵류), 곰보빵 ",380f),
			    FoodEntity("밀 가공(빵류), 꽈배기 ",404f),
			    FoodEntity("밀 가공(빵류), 도우넛, 링 ",426f),
			    FoodEntity("밀 가공(빵류), 도우넛, 이스트 ",271.6f),
			    FoodEntity("밀 가공(빵류), 도우넛, 케이크 ",262.5f),
			    FoodEntity("밀 가공(빵류), 도우넛, 팥 ",347f),
			    FoodEntity("밀 가공(빵류), 롤빵, 소프트롤 ",316f),
			    FoodEntity("밀 가공(빵류), 롤빵, 하드롤 ",293f),
			    FoodEntity("밀 가공(빵류), 마늘빵 ",500f),
			    FoodEntity("밀 가공(빵류), 머핀, 우유 ",296f),
			    FoodEntity("밀 가공(빵류), 머핀, 잉글리쉬머핀 ",234f),
			    FoodEntity("밀 가공(빵류), 모닝빵 ",331f),
			    FoodEntity("밀 가공(빵류), 모카빵 ",316f),
			    FoodEntity("밀 가공(빵류), 바게트빵 ",279f),
			    FoodEntity("밀 가공(빵류), 베이글, 달걀 ",278f),
			    FoodEntity("밀 가공(빵류), 식빵 ",284f),
			    FoodEntity("밀 가공(빵류), 식빵, 옥수수 ",275f),
			    FoodEntity("밀 가공(빵류), 식빵, 우유 ",285f),
			    FoodEntity("밀 가공(빵류), 식빵, 토스트 ",293f),
			    FoodEntity("밀 가공(빵류), 옥수수빵 ",314f),
			    FoodEntity("밀 가공(빵류), 잼빵 ",297f),
			    FoodEntity("밀 가공(빵류), 찐빵, 단호박소 ",239f),
			    FoodEntity("밀 가공(빵류), 찐빵, 채소 ",231f),
			    FoodEntity("밀 가공(빵류), 찐빵, 팥 ",244f),
			    FoodEntity("밀 가공(빵류), 카스텔라 ",324f),
			    FoodEntity("밀 가공(빵류), 카스텔라, 감 3%",238f),
			    FoodEntity("밀 가공(빵류), 케이크, 과일(후르츠) ",323f),
			    FoodEntity("밀 가공(빵류), 케이크, 롤 ",365f),
			    FoodEntity("밀 가공(빵류), 케이크, 배 ",296f),
			    FoodEntity("밀 가공(빵류), 케이크, 생크림, 블루베리 ",249f),
			    FoodEntity("밀 가공(빵류), 케이크, 쇼튼드 ",344f),
			    FoodEntity("밀 가공(빵류), 케이크, 스펀지 ",352f),
			    FoodEntity("밀 가공(빵류), 케이크, 엔젤푸드 ",258f),
			    FoodEntity("밀 가공(빵류), 케이크, 초콜렛 ",453f),
			    FoodEntity("밀 가공(빵류), 케이크, 치즈 ",321f),
			    FoodEntity("밀 가공(빵류), 케이크, 컵 ",213.5f),
			    FoodEntity("밀 가공(빵류), 케이크, 파운드 ",414f),
			    FoodEntity("밀 가공(빵류), 크로아상 ",448f),
			    FoodEntity("밀 가공(빵류), 크로아상, 버터 ",405f),
			    FoodEntity("밀 가공(빵류), 크로켓 ",307f),
			    FoodEntity("밀 가공(빵류), 크로켓, 채소 ",301f),
			    FoodEntity("밀 가공(빵류), 크림빵 ",274f),
			    FoodEntity("밀 가공(빵류), 크림빵, 버터 ",383f),
			    FoodEntity("밀 가공(빵류), 팥빵 ",293f),
			    FoodEntity("밀 가공(빵류), 패이스트리 ",457f),
			    FoodEntity("밀 가공(빵류), 패이스트리, 과일(후르츠)  ",371f),
			    FoodEntity("밀 가공(빵류), 패이스트리, 치즈 ",374f),
			    FoodEntity("밀 가공(빵류), 팬케이크 ",227f),
			    FoodEntity("보리 가공(기타), 겉보리, 압맥 ",348f),
			    FoodEntity("보리 가공(기타), 겉보리, 할맥 ",351f),
			    FoodEntity("보리 가공(기타), 볶은보리 ",360f),
			    FoodEntity("보리 가공(기타), 엿기름 ",338f),
			    FoodEntity("보리,겉보리, 보리쌀",322f),
			    FoodEntity("보리밥,보리밥",294f),
			    FoodEntity("볶음밥,햄볶음밥",518.7f),
			    FoodEntity("빵,슈크림",170.8f),
			    FoodEntity("빵,크로아상",448f),
			    FoodEntity("빵,호빵, 고기소",175.7f),
			    FoodEntity("샌드위치, 달걀, 치즈",349.5f),
			    FoodEntity("샌드위치, 닭고기 ",283f),
			    FoodEntity("샌드위치, 생선 ",273f),
			    FoodEntity("샌드위치, 소고기 ",249f),
			    FoodEntity("샌드위치, 햄, 치즈 ",218f),
			    FoodEntity("샌드위치,샌드위치",181.5f),
			    FoodEntity("수수 가공(떡류), 수수경단 ",218f),
			    FoodEntity("스프,감자스프, 감자스프(오뚜기)",380f),
			    FoodEntity("스프,쇠고기야채스프, 분말",344f),
			    FoodEntity("스프,쇠고기야채스프, 쇠고기스프(오뚜기)",355f),
			    FoodEntity("스프,야채스프, 야채스프(오뚜기)",350f),
			    FoodEntity("스프,양송이스프, 양송이수프(오뚜기)",360f),
			    FoodEntity("스프,옥수수스프, 옥수수스프(오뚜기)",360f),
			    FoodEntity("스프,크림스프, 아스파라거스",366f),
			    FoodEntity("스프,크림스프, 크림스프(오뚜기)",355f),
			    FoodEntity("스프,호박스프, 호박스프(오뚜기)",395f),
			    FoodEntity("시리얼 ",116.1f),
			    FoodEntity("시리얼, 과즙",116.4f),
			    FoodEntity("시리얼, 꿀",115.8f),
			    FoodEntity("시리얼, 쌀",379f),
			    FoodEntity("시리얼, 아몬드",414f),
			    FoodEntity("시리얼, 코코넛",114.6f),
			    FoodEntity("시리얼, 현미",390f),
			    FoodEntity("시리얼,기타, 라이스크리스피",111f),
			    FoodEntity("시리얼,기타, 코코넛첵스",113.3f),
			    FoodEntity("시리얼,기타, 코코링",376f),
			    FoodEntity("시리얼,기타, 코코팝스",376f),
			    FoodEntity("시리얼,기타, 콘첵스",376f),
			    FoodEntity("시리얼,기타, 하니팝스",114.9f),
			    FoodEntity("시리얼,기타, 후르트링",114.6f),
			    FoodEntity("시리얼,푸레이크, 아몬드푸레이크",406f),
			    FoodEntity("시리얼,푸레이크, 현미푸레이크",376f),
			    FoodEntity("시리얼,푸로스트, 콘푸로스트",387f),
			    FoodEntity("옥수수 가공(과자류), 콘칩 ",518f),
			    FoodEntity("옥수수 가공(과자류), 팝콘 ",536f),
			    FoodEntity("옥수수 가공(기타), 콘샐러드 ",104f),
			    FoodEntity("옥수수 가공(면류), 옥수수묵 ",55f),
			    FoodEntity("옥수수 가공(통조림), 가당 ",91f),
			    FoodEntity("옥수수 가공(통조림), 홀커넬 ",82f),
			    FoodEntity("옥수수, 찰옥수수, 찐것 ",132f),
			    FoodEntity("옥수수죽, 레토르트 ",86f),
			    FoodEntity("울면,울면, 인스턴트",860f),
			    FoodEntity("율무 가공(밥죽류), 죽 ",44f),
			    FoodEntity("이유식,이유식",170.4f),
			    FoodEntity("잣 가공(밥죽류), 죽 ",31f),
			    FoodEntity("죽, 참치죽, 레토르트 ",161f),
			    FoodEntity("죽, 팥죽, 레토르트",117f),
			    FoodEntity("죽,호박죽, 레토르트",220.5f),
			    FoodEntity("참깨 가공(과자류), 엿강정 ",538f),
			    FoodEntity("참깨 가공(밥죽류), 죽 ",38f),
			    FoodEntity("찹쌀 가공(과자류), 다식, 검정깨 ",475f),
			    FoodEntity("찹쌀 가공(과자류), 다식, 송화 ",326f),
			    FoodEntity("찹쌀 가공(과자류), 산자 ",417f),
			    FoodEntity("찹쌀 가공(과자류), 유과 ",382f),
			    FoodEntity("찹쌀 가공(과자류), 전병 ",446f),
			    FoodEntity("찹쌀 가공(떡류), 경단, 카스텔라",240f),
			    FoodEntity("찹쌀 가공(떡류), 모듬찰떡 ",223f),
			    FoodEntity("찹쌀 가공(떡류), 약식 ",259f),
			    FoodEntity("찹쌀 가공(떡류), 인절미, 콩고물 ",221f),
			    FoodEntity("찹쌀 가공(떡류), 인절미, 팥고물 ",204f),
			    FoodEntity("찹쌀 가공(떡류), 찰시루떡 ",238f),
			    FoodEntity("찹쌀 가공(떡류), 찹쌀떡 ",236f),
			    FoodEntity("찹쌀 가공(빵류), 찹쌀도우넛 ",296f),
			    FoodEntity("커스타드, 달걀 ",105f),
			    FoodEntity("케이크,당근케이크",290.5f),
			    FoodEntity("콩소메,콩소메, 분말",137f),
			    FoodEntity("통밀,밀쌀",292.5f),
			    FoodEntity("통밀,통밀",372f),
			    FoodEntity("푸딩, 커스터드 ",126f),
			    FoodEntity("피자,페페로니",444f),
			    FoodEntity("피자,피자",403.5f),
			    FoodEntity("핫도그,핫도그",247f),
			    FoodEntity("햄버거, 치즈버거 ",454.5f),
			    FoodEntity("호밀 가공(빵류), 호밀빵 ",264f),
			    FoodEntity("감자 가공(과자류), 감자칩, 구운것 ",454f),
			    FoodEntity("감자 가공(과자류), 감자칩, 튀긴것 ",532f),
			    FoodEntity("감자 가공(기타), 감자샐러드 ",121f),
			    FoodEntity("감자 가공(기타), 감자튀김(후렌치후라이), 튀긴것 ",319f),
			    FoodEntity("감자 가공(기타), 으깬감자, 우유 ",81f),
			    FoodEntity("감자 가공(기타), 해쉬브라운, 튀긴것 ",334f),
			    FoodEntity("감자, 껍질제거, 구운것 ",72f),
			    FoodEntity("감자, 삶은것 ",66f),
			    FoodEntity("감자, 찐것 ",70f),
			    FoodEntity("감자,감자, 으깬것",83f),
			    FoodEntity("고구마 가공(기타), 당조림 ",185.9f),
			    FoodEntity("고구마, 구운것 ",161.2f),
			    FoodEntity("고구마, 찐것 ",130f),
			    FoodEntity("곤약[구약나물] 가공(기타), 곤약, 국수형 ",6f),
			    FoodEntity("곤약[구약나물] 가공(기타), 곤약, 판형 ",12f),
			    FoodEntity("마, 장마, 삶은것 ",59f),
			    FoodEntity("천마, 찐것 ",81f),
			    FoodEntity("토란, 삶은것 ",61f),
			    FoodEntity("감 가공(기타), 감조청 ",201f),
			    FoodEntity("과당 ",370f),
			    FoodEntity("껌, 풍선껌 ",387f),
			    FoodEntity("꿀 ",294f),
			    FoodEntity("꿀, 들깨꿀 ",292f),
			    FoodEntity("꿀, 밤꿀 ",292f),
			    FoodEntity("당밀, 가공당 ",265f),
			    FoodEntity("당밀,정제당",27.2f),
			    FoodEntity("로얄제리 ",138f),
			    FoodEntity("물엿 ",293f),
			    FoodEntity("사탕, 박하사탕 ",376f),
			    FoodEntity("사탕, 알사탕 ",39.4f),
			    FoodEntity("사탕,사탕",37.4f),
			    FoodEntity("사탕,사탕, 누가사탕,땅콩",413f),
			    FoodEntity("사탕,사탕, 누가사탕,살구",37f),
			    FoodEntity("사탕무우 가공(기타), 농축액 ",27.2f),
			    FoodEntity("양갱, 팥 ",286f),
			    FoodEntity("엿, 고구마 ",263f),
			    FoodEntity("엿,깨엿강정",384f),
			    FoodEntity("엿,흰엿",102.9f),
			    FoodEntity("젤리 ",327f),
			    FoodEntity("조청, 고구마 ",352f),
			    FoodEntity("조청, 도라지 ",352f),
			    FoodEntity("조청, 배 ",238f),
			    FoodEntity("조청, 산수유 ",299f),
			    FoodEntity("조청, 쌀 ",370f),
			    FoodEntity("조청, 오가피 ",286f),
			    FoodEntity("초콜렛 ",81.45f),
			    FoodEntity("초콜렛, 다크 ",524f),
			    FoodEntity("초콜렛, 땅콩 ",518f),
			    FoodEntity("초콜렛, 밀크(우유) ",572f),
			    FoodEntity("초콜렛, 밀크(우유), 라이스(쌀)시리얼 ",511f),
			    FoodEntity("초콜렛, 밀크(우유), 아몬드 ",526f),
			    FoodEntity("초콜렛, 새알 ",74.1f),
			    FoodEntity("초콜렛, 스위트 ",507f),
			    FoodEntity("초콜렛, 초코바 ",75f),
			    FoodEntity("초콜렛, 화이트 ",539f),
			    FoodEntity("카라멜, 밀크(우유)",423f),
			    FoodEntity("강낭콩, 삶은것 ",156f),
			    FoodEntity("녹두 가공(면류), 녹두묵 ",37f),
			    FoodEntity("녹두, 삶은것 ",133f),
			    FoodEntity("대두 가공(두부류), 두부 ",88f),
			    FoodEntity("대두 가공(두부류), 비지 ",74f),
			    FoodEntity("대두 가공(두부류), 순두부 ",55f),
			    FoodEntity("대두 가공(두부류), 연두부 ",62f),
			    FoodEntity("대두 가공(음료류), 두유 ",70f),
			    FoodEntity("대두, 검정콩, 청자3호, 볶은것 ",452f),
			    FoodEntity("대두, 노란콩, 대풍, 볶은것 ",460f),
			    FoodEntity("대두, 노란콩, 삶은것 ",182f),
			    FoodEntity("동부, 삶은것 ",141f),
			    FoodEntity("두유,가공두유, 베지밀",70f),
			    FoodEntity("라이마빈스, 삶은것 ",115f),
			    FoodEntity("완두콩, 삶은것 ",116f),
			    FoodEntity("잠두, 삶은것 ",110f),
			    FoodEntity("팥 가공(기타), 페이스트 ",155f),
			    FoodEntity("팥, 검정팥, 삶은것 ",145f),
			    FoodEntity("팥, 붉은팥, 삶은것 ",200f),
			    FoodEntity("개암, 볶은것 ",684f),
			    FoodEntity("도토리 가공(면류), 도토리묵 ",43f),
			    FoodEntity("들깨, 마른것 ",501f),
			    FoodEntity("땅콩 가공(기타), 조미품",638f),
			    FoodEntity("땅콩 가공(기타), 커피맛 ",60.8f),
			    FoodEntity("땅콩, 검정땅콩, 마른것 ",574f),
			    FoodEntity("땅콩, 대립종, 마른것 ",571f),
			    FoodEntity("땅콩, 마른것 ",568f),
			    FoodEntity("땅콩, 볶은것 ",580f),
			    FoodEntity("땅콩, 삶은것 ",318f),
			    FoodEntity("땅콩, 소립종, 마른것 ",564f),
			    FoodEntity("땅콩, 중립종, 마른것 ",549f),
			    FoodEntity("마카다미아넛 가공(기타), 조미품",720f),
			    FoodEntity("밤 가공(통조림), 통조림 ",225f),
			    FoodEntity("밤, 구운것 ",166f),
			    FoodEntity("밤, 마른것 ",377f),
			    FoodEntity("밤, 삶은것 ",96f),
			    FoodEntity("밤, 축파, 구운것 ",185f),
			    FoodEntity("밤,밤넥타",54f),
			    FoodEntity("보리밥 열매, 마른것 ",354f),
			    FoodEntity("브라질너트, 마른것 ",655f),
			    FoodEntity("브라질너트, 볶은것 ",669f),
			    FoodEntity("아몬드 가공(기타), 조미품",615f),
			    FoodEntity("아몬드, 마른것 ",598f),
			    FoodEntity("은행, 삶은것 ",171f),
			    FoodEntity("잣 가공(두부류), 잣두부 ",86f),
			    FoodEntity("잣, 마른것 ",640f),
			    FoodEntity("잣, 볶은것 ",708f),
			    FoodEntity("참깨, 검정깨, 볶은것 ",587f),
			    FoodEntity("참깨, 흰깨, 볶은것 ",601f),
			    FoodEntity("캐슈넛 가공(기타), 조미품 ",576f),
			    FoodEntity("코코넛 가공(음료류), 코코넛밀크",230f),
			    FoodEntity("코코넛, 마른것 ",660f),
			    FoodEntity("코코넛, 볶은것 ",592f),
			    FoodEntity("코코넛, 코코넛수",19f),
			    FoodEntity("피스타치오넛 가공(기타), 조미품 ",580f),
			    FoodEntity("피스타치오넛, 마른것 ",562f),
			    FoodEntity("피칸 가공(기타), 조미품 ",710f),
			    FoodEntity("피칸, 마른것 ",691f),
			    FoodEntity("호두, 마른것 ",663f),
			    FoodEntity("호두, 볶은것 ",671f),
			    FoodEntity("가시오가피, 순, 데친것 ",39f),
			    FoodEntity("가지 가공(기타), 가지절임 ",23f),
			    FoodEntity("가지, 데친것 ",15f),
			    FoodEntity("고비 건조, 데친것 ",20f),
			    FoodEntity("고비, 데친것 ",21f),
			    FoodEntity("고사리, 데친것 ",26f),
			    FoodEntity("고추 ,잎, 데친것 ",41f),
			    FoodEntity("곤달비, 데친것 ",35f),
			    FoodEntity("곰취, 데친것 ",25f),
			    FoodEntity("공심채, 데친것 ",21f),
			    FoodEntity("국화꽃, 데친것 ",23f),
			    FoodEntity("근대, 데친것 ",28f),
			    FoodEntity("김치, 갓김치 ",51f),
			    FoodEntity("김치, 고들빼기 ",88f),
			    FoodEntity("김치, 깍두기 ",39f),
			    FoodEntity("김치, 나박김치 ",14f),
			    FoodEntity("김치, 동치미 ",16f),
			    FoodEntity("김치, 배추김치 ",25f),
			    FoodEntity("김치, 백김치 ",42f),
			    FoodEntity("김치, 열무김치 ",34f),
			    FoodEntity("김치, 오이소박이 ",35f),
			    FoodEntity("김치, 유채김치 ",62f),
			    FoodEntity("김치, 총각김치 ",37f),
			    FoodEntity("김치, 파김치 ",59f),
			    FoodEntity("김치,무청김치",9.2f),
			    FoodEntity("깻잎 가공(통조림), 통조림 ",76f),
			    FoodEntity("깻잎(들깻잎), 데친것 ",24f),
			    FoodEntity("깻잎(들깻잎), 찐것 ",30f),
			    FoodEntity("꽃양배추, 데친것 ",20f),
			    FoodEntity("냉이, 데친것 ",45f),
			    FoodEntity("넘취, 데친것 ",29f),
			    FoodEntity("녹색완두콩 가공(통조림), 미숙, 통조림",98f),
			    FoodEntity("녹색완두콩, 미숙, 데친것",110f),
			    FoodEntity("누룩치, 잎, 데친것 ",38f),
			    FoodEntity("누룩치, 줄기, 데친것 ",25f),
			    FoodEntity("다채,다채",12f),
			    FoodEntity("당귀,잎, 노지재배",46.9f),
			    FoodEntity("당귀,잎, 양액재배",28f),
			    FoodEntity("당근 가공(음료), 당근캔주스 ",40f),
			    FoodEntity("당근, 뿌리, 데친것 ",35f),
			    FoodEntity("도라지, 데친것 ",44f),
			    FoodEntity("동아, 데친것 ",16f),
			    FoodEntity("두릅, 데친것 ",37f),
			    FoodEntity("두릅, 땅두릅, 데친것 ",14f),
			    FoodEntity("두릅, 땅두릅, 잎, 데친것 ",61f),
			    FoodEntity("두릅, 땅두릅, 줄기, 데친것 ",16f),
			    FoodEntity("떡취,떡취",31f),
			    FoodEntity("리크, 데친것 ",22f),
			    FoodEntity("마늘 가공(기타), 마늘장아찌 ",53f),
			    FoodEntity("마늘 가공(기타), 마늘쫑장아찌 ",138f),
			    FoodEntity("마늘 페이스트 ",171f),
			    FoodEntity("마늘, 남도마늘, 구근, 데친것 ",49f),
			    FoodEntity("마늘쨈,마늘쑥쨈",38.8f),
			    FoodEntity("마늘쨈,마늘호박쨈",35f),
			    FoodEntity("머위, 잎자루, 데친것 ",20f),
			    FoodEntity("머위, 잎자루, 삶은것 ",24f),
			    FoodEntity("모시딱지,모시딱지, 울릉도산채",229f),
			    FoodEntity("무 가공(기타), 단무지 ",12f),
			    FoodEntity("무 가공(기타), 무말랭이",267f),
			    FoodEntity("무 가공(기타), 무시래기, 데친것 ",47f),
			    FoodEntity("무 가공(기타), 무장아찌 ",87f),
			    FoodEntity("무 가공(기타), 무절임(무짠지)",17f),
			    FoodEntity("무, 순무 가공(기타), 무청절임 ",29f),
			    FoodEntity("무, 순무 가공(기타), 순무절임",23f),
			    FoodEntity("무, 순무, 무청, 데친것 ",22f),
			    FoodEntity("무, 순무, 뿌리, 데친것 ",21f),
			    FoodEntity("무, 열무, 데친것 ",24f),
			    FoodEntity("무꼬투리,무꼬투리",6f),
			    FoodEntity("물쑥, 데친것 ",51f),
			    FoodEntity("미나리, 데친것 ",26f),
			    FoodEntity("미나리, 돌미나리, 데친것, 야생 ",19f),
			    FoodEntity("민들레, 데친것 ",29f),
			    FoodEntity("바셀라, 데친것 ",15f),
			    FoodEntity("박 가공(기타), 박오가리, 데친것 ",28f),
			    FoodEntity("방울다다기양배추, 데친것 ",49f),
			    FoodEntity("배추, 데친것 ",17f),
			    FoodEntity("배추, 봄동, 데친것 ",22f),
			    FoodEntity("부추, 재래종, 데친것 ",20f),
			    FoodEntity("브로콜리, 데친것 ",33f),
			    FoodEntity("브로콜리, 삶은것 ",27f),
			    FoodEntity("비름, 데친것 ",34f),
			    FoodEntity("비트 가공(통조림), 뿌리, 비트피클",66f),
			    FoodEntity("비트, 뿌리, 데친것 ",24f),
			    FoodEntity("비트, 잎, 데친것 ",15f),
			    FoodEntity("생강 가공(과자류), 편강 ",361f),
			    FoodEntity("생강 가공(기타), 생강피클",19f),
			    FoodEntity("생강 페이스트 ",43f),
			    FoodEntity("섬초롱, 데친것 ",34f),
			    FoodEntity("쇠귀나물, 뿌리, 데친것 ",128f),
			    FoodEntity("숙주나물, 데친것 ",12f),
			    FoodEntity("시금치, 데친것 ",23f),
			    FoodEntity("시금치,시금치, 삶은것",8f),
			    FoodEntity("쑥, 데친것 ",33f),
			    FoodEntity("쑥갓, 데친것 ",19f),
			    FoodEntity("씀바귀, 데친것 ",31f),
			    FoodEntity("아스파라거스, 가공(통조림), 통조림 ",14f),
			    FoodEntity("아스파라거스, 데친것 ",23f),
			    FoodEntity("아욱, 데친것 ",21f),
			    FoodEntity("야콘,잎",35.7f),
			    FoodEntity("양배추 가공(기타), 코올슬로우(샐러드)",69f),
			    FoodEntity("양배추, 데친것 ",27f),
			    FoodEntity("양파 가공(기타), 양파링, 튀김옷입혀튀긴것",332f),
			    FoodEntity("양파, 데친것 ",38f),
			    FoodEntity("엄나무(개두릅), 잎, 데친것 ",31f),
			    FoodEntity("엉겅퀴, 숙건 ",279f),
			    FoodEntity("연근, 데친것 ",68f),
			    FoodEntity("염교(락교) 가공(기타), 염교(락교)장아찌 ",85f),
			    FoodEntity("영아자, 데친것 ",36f),
			    FoodEntity("오이 가공(기타),  오이절임(오이지)  ",17f),
			    FoodEntity("오이 가공(기타), 오이피클 ",106f),
			    FoodEntity("오크라, 데친것 ",33f),
			    FoodEntity("왜우산풀, 숙건 ",290f),
			    FoodEntity("우엉, 데친것 ",70f),
			    FoodEntity("울외 가공(기타), 울외장아찌 ",67f),
			    FoodEntity("워터크레스,워터크레스",20f),
			    FoodEntity("유채, 서양종, 줄기잎, 데친것 ",31f),
			    FoodEntity("유채,꽃대, 재래종",8.75f),
			    FoodEntity("유채,꽃대, 재래종,삶은것",7.75f),
			    FoodEntity("죽순 가공(통조림), 통조림 ",16f),
			    FoodEntity("죽순, 데친것 ",30f),
			    FoodEntity("질경이, 데친것 ",45f),
			    FoodEntity("창출나물,창출나물",40f),
			    FoodEntity("취나물, 참취, 건조, 데친것 ",55f),
			    FoodEntity("취나물, 참취, 데친것 ",21f),
			    FoodEntity("콜라비, 데친것 ",21f),
			    FoodEntity("콩나물, 데친것 ",42f),
			    FoodEntity("토란대, 줄기, 건조, 데친것",20f),
			    FoodEntity("토란대, 줄기, 데친것 ",20f),
			    FoodEntity("토마토 가공(기타), 토마토페이스트 ",20f),
			    FoodEntity("토마토 가공(음료), 토마토주스 ",20f),
			    FoodEntity("토마토 가공(통조림), 토마토퓨레통조림 ",89f),
			    FoodEntity("토마토 가공(통조림), 통조림 ",20f),
			    FoodEntity("토마토, 데친것 ",17f),
			    FoodEntity("풋고추,개량종",23.86f),
			    FoodEntity("향채,향채",27f),
			    FoodEntity("호박, 국수호박, 데친것 ",16f),
			    FoodEntity("호박, 늙은호박, 데친것 ",30f),
			    FoodEntity("호박, 단호박, 데친것 ",30f),
			    FoodEntity("호박, 애호박, 데친것 ",24f),
			    FoodEntity("호박, 잎, 데친것 ",32f),
			    FoodEntity("호박, 잎, 찐것 ",31f),
			    FoodEntity("호박, 쥬키니, 데친것 ",11f),
			    FoodEntity("홍무,홍무",14f),
			    FoodEntity("홑잎나물, 데친것 ",35f),
			    FoodEntity("느타리버섯, 데친것 ",31f),
			    FoodEntity("느타리버섯, 참타리버섯, 데친것",20f),
			    FoodEntity("목이버섯, 데친것 ",13f),
			    FoodEntity("송이버섯 가공(통조림), 통조림 ",14f),
			    FoodEntity("양송이버섯 가공(통조림), 통조림 ",16f),
			    FoodEntity("큰느타리버섯(새송이버섯), 데친것 ",21f),
			    FoodEntity("팽이버섯, 데친것, 재배 ",17f),
			    FoodEntity("표고버섯, 건조, 데친것, 참나무재배 ",55f),
			    FoodEntity("표고버섯, 데친것, 참나무재배 ",18f),
			    FoodEntity("감 가공(기타), 감말랭이 ",247f),
			    FoodEntity("감 가공(기타), 곶감 ",237f),
			    FoodEntity("감 가공(기타), 단감, 잼 ",225f),
			    FoodEntity("감 가공(음료), 주스 ",41f),
			    FoodEntity("구아바 가공(음료), 넥타(과육 20%) ",51f),
			    FoodEntity("구아바 가공(음료), 주스(과즙 10%) ",51f),
			    FoodEntity("귤 가공(기타), 잼 ",309f),
			    FoodEntity("귤 가공(음료), 과일주스 ",39f),
			    FoodEntity("귤 가공(음료), 과일주스, 무가당 ",49f),
			    FoodEntity("귤 가공(통조림), 통조림, 무가당 ",64f),
			    FoodEntity("귤쥬스,농축과즙",414f),
			    FoodEntity("대추, 마른것 ",299f),
			    FoodEntity("대추야자, 마른것 ",266f),
			    FoodEntity("딸기 가공(기타), 잼 ",254f),
			    FoodEntity("딸기쥬스,넥타",108f),
			    FoodEntity("딸리,개량종",35f),
			    FoodEntity("라임 가공(음료), 과일주스 ",25f),
			    FoodEntity("레몬 가공(음료), 과일주스",52f),
			    FoodEntity("레몬쥬스,농축과즙",39f),
			    FoodEntity("매실 가공(기타), 농축액 ",281f),
			    FoodEntity("매실 가공(기타), 매실절임 ",33f),
			    FoodEntity("매실음료 ",55f),
			    FoodEntity("머루, 가공(음료), 과일주스",81f),
			    FoodEntity("무화과 가공(통조림), 통조림 ",81f),
			    FoodEntity("무화과, 마른것 ",271f),
			    FoodEntity("바나나, 마른것 ",483f),
			    FoodEntity("배 가공(음료), 과즙 ",52f),
			    FoodEntity("배 가공(음료), 넥타 ",106f),
			    FoodEntity("배 가공(통조림), 통조림, 일본배",23.4f),
			    FoodEntity("배쥬스,농축과배쥬스,농축과즙",53f),
			    FoodEntity("버찌 가공(통조림), 통조림 ",74f),
			    FoodEntity("복숭아 가공(기타), 당절임 ",311f),
			    FoodEntity("복숭아 가공(기타), 잼 ",245f),
			    FoodEntity("복숭아 가공(음료), 넥타 ",45f),
			    FoodEntity("복숭아 가공(통조림), 백도, 통조림 ",71f),
			    FoodEntity("복숭아 가공(통조림), 황도, 통조림 ",59f),
			    FoodEntity("블루베리 가공(기타), 잼 ",181f),
			    FoodEntity("블루베리 가공(통조림), 통조림 ",88f),
			    FoodEntity("비파 가공(통조림), 통조림 ",81f),
			    FoodEntity("사과 가공(기타), 잼 ",256f),
			    FoodEntity("사과 가공(음료), 넥타 ",53f),
			    FoodEntity("사과 가공(음료), 농축과즙 주스 ",43f),
			    FoodEntity("사과 가공(음료), 주스, 가당 ",49f),
			    FoodEntity("사과 가공(음료), 주스, 무가당 ",43f),
			    FoodEntity("사과 가공(통조림), 통조림 ",66f),
			    FoodEntity("사과, 마른것 ",275f),
			    FoodEntity("살구 가공(기타), 잼 ",271f),
			    FoodEntity("살구 가공(음료), 넥타 ",41f),
			    FoodEntity("살구 가공(통조림), 통조림 ",48f),
			    FoodEntity("살구, 마른것 ",288f),
			    FoodEntity("오렌지 가공(기타), 마멀레이드 ",223f),
			    FoodEntity("오렌지 가공(음료), 과일주스",42f),
			    FoodEntity("오렌지 가공(음료), 주스, 가당, 칼슘강화 ",53f),
			    FoodEntity("오렌지 가공(음료), 주스, 무가당 ",36f),
			    FoodEntity("오미자 가공(기타), 농축액 ",259f),
			    FoodEntity("오미자, 마른것 ",362f),
			    FoodEntity("올리브 가공(기타), 숙과피클 ",118f),
			    FoodEntity("올리브 가공(기타), 청과피클 ",116f),
			    FoodEntity("올리브, 마른것 ",307f),
			    FoodEntity("유자 가공(기타), 농축액 ",243f),
			    FoodEntity("자두, 가공(기타), 건자두 ",221f),
			    FoodEntity("자두쥬스,일본자두넥타",92f),
			    FoodEntity("자몽 가공(음료), 과일주스",40f),
			    FoodEntity("크랜베리 가공(음료), 주스칵테일 ",54f),
			    FoodEntity("파인애플 가공(음료), 과일주스",41f),
			    FoodEntity("파인애플 가공(음료), 과즙음료(과즙 50%)",51f),
			    FoodEntity("파인애플 가공(음료), 넥타 ",71f),
			    FoodEntity("파인애플 가공(음료), 농축과즙 주스 ",41f),
			    FoodEntity("파인애플 가공(통조림), 통조림 ",62f),
			    FoodEntity("패션후르츠 가공(음료), 과일주스",64f),
			    FoodEntity("패션후르츠,패션후르츠",97f),
			    FoodEntity("포도 가공(기타), 건포도, 마른것 ",277f),
			    FoodEntity("포도 가공(기타), 잼 ",257f),
			    FoodEntity("포도 가공(음료), 과일주스",40f),
			    FoodEntity("포도 가공(음료), 과즙음료 ",49f),
			    FoodEntity("포도 가공(음료), 넥타 ",66f),
			    FoodEntity("포도 가공(음료), 농축과즙 주스 ",35f),
			    FoodEntity("포도 가공(음료), 캔주스 ",60f),
			    FoodEntity("포도 가공(음료), 포도즙 ",47f),
			    FoodEntity("포도 가공(통조림), 통조림 ",57f),
			    FoodEntity("후르츠샐러드, 통조림 ",82f),
			    FoodEntity("후르츠칵테일, 통조림 ",83f),
			    FoodEntity("거위, 살코기, 구운것 ",238f),
			    FoodEntity("거위부산물,간, 거위부산물,간,튀긴것",146.4f),
			    FoodEntity("고래고기 가공(기타), 붉은살, 염장품 ",162f),
			    FoodEntity("고래고기,꼬리, 고래고기,꼬리,꼬리살",253f),
			    FoodEntity("고래고기,비계",45f),
			    FoodEntity("고래고기,염장품, 고래고기,염장품,지육",33.6f),
			    FoodEntity("닭 가공(기타), 가슴살, 튀김, 튀김옷 ",261f),
			    FoodEntity("닭 가공(기타), 날개, 튀김, 튀김옷 ",324f),
			    FoodEntity("닭 가공(기타), 넓적다리, 튀김, 튀김옷 ",270f),
			    FoodEntity("닭 가공(기타), 다리, 튀김, 튀김옷 ",327f),
			    FoodEntity("닭 가공(기타), 목, 튀김, 튀김옷 ",330f),
			    FoodEntity("닭 가공(기타), 살코기, 튀김, 튀김옷 ",289f),
			    FoodEntity("닭 가공(기타), 통닭, 튀긴것",280f),
			    FoodEntity("닭 부산물, 간, 삶은것 ",167f),
			    FoodEntity("닭 부산물, 모래주머니, 구운것 ",158f),
			    FoodEntity("닭 부산물, 심장, 삶은것 ",184f),
			    FoodEntity("닭고기, 가슴, 삶은것 ",236f),
			    FoodEntity("닭고기, 가슴살, 구운것 ",164f),
			    FoodEntity("닭고기, 구운것 ",247f),
			    FoodEntity("닭고기, 날개, 구운것 ",291f),
			    FoodEntity("닭고기, 날개, 삶은것 ",243f),
			    FoodEntity("닭고기, 넓적다리살, 구운것 ",177f),
			    FoodEntity("닭고기, 다리살, 구운것 ",174f),
			    FoodEntity("닭고기, 살코기, 구운것 ",190f),
			    FoodEntity("닭고기, 살코기, 삶은것 ",142f),
			    FoodEntity("닭고기, 영계, 삶은것 ",251f),
			    FoodEntity("닭고기,다리살, 삶은것",208f),
			    FoodEntity("닭고기,성계, 닭고기,성계,구이통닭",145.8f),
			    FoodEntity("돼지 가공(기타), 돈가스, 튀김",365f),
			    FoodEntity("돼지 가공(기타), 바베큐, 구운것 ",103.8f),
			    FoodEntity("돼지 가공(기타), 베이컨",304f),
			    FoodEntity("돼지 가공(기타), 베이컨, 구운것",540f),
			    FoodEntity("돼지 가공(기타), 순대 ",114f),
			    FoodEntity("돼지 가공(기타), 족발, 조미품",266f),
			    FoodEntity("돼지 가공(소시지), 건조소시지 ",497f),
			    FoodEntity("돼지 가공(소시지), 리용소시지 ",192f),
			    FoodEntity("돼지 가공(소시지), 볼로냐소시지 ",251f),
			    FoodEntity("돼지 가공(소시지), 위너(비엔나)소시지 ",297f),
			    FoodEntity("돼지 가공(소시지), 이탈리안소시지 ",346f),
			    FoodEntity("돼지 가공(소시지), 프랑크푸르트소시지 ",272f),
			    FoodEntity("돼지 가공(소시지), 핫도그소시지",82.8f),
			    FoodEntity("돼지 가공(햄), 등심 ",131f),
			    FoodEntity("돼지 가공(햄), 런천미트 ",251f),
			    FoodEntity("돼지 가공(햄), 로스 ",128f),
			    FoodEntity("돼지 가공(햄), 본레스",166f),
			    FoodEntity("돼지 가공(햄), 본레스, 구운것",145f),
			    FoodEntity("돼지 가공(햄), 통조림, 구운것 ",226f),
			    FoodEntity("돼지 부산물, 간, 삶은것 ",165f),
			    FoodEntity("돼지 부산물, 대장, 삶은것 ",179f),
			    FoodEntity("돼지 부산물, 소장(곱창), 삶은것 ",171f),
			    FoodEntity("돼지 부산물, 신장, 삶은것 ",151f),
			    FoodEntity("돼지 부산물, 심장, 삶은것 ",148f),
			    FoodEntity("돼지 부산물, 족발, 삶은것 ",239f),
			    FoodEntity("돼지 부산물, 허파, 삶은것 ",99f),
			    FoodEntity("돼지고기, 갈비, 구운것 ",368f),
			    FoodEntity("돼지고기, 갈비, 삶은것 ",347f),
			    FoodEntity("돼지고기, 뒷다리, 구운것 ",299f),
			    FoodEntity("돼지고기, 등심, 구운것 ",242f),
			    FoodEntity("돼지고기, 등심, 삶은것 ",219f),
			    FoodEntity("돼지고기, 사태, 구운것 ",215f),
			    FoodEntity("돼지고기, 삼겹살, 구운것 ",493f),
			    FoodEntity("돼지고기, 안심, 구운것 ",220f),
			    FoodEntity("돼지고기, 어깨등심, 구운것 ",297f),
			    FoodEntity("돼지고기,등심, 브로일한것",242f),
			    FoodEntity("돼지고기,목살, 양념한것",129f),
			    FoodEntity("돼지고기,안심, 브로일한것",201f),
			    FoodEntity("사슴고기, 구운것 ",158f),
			    FoodEntity("소 가공(기타), 양지국물(한우)",4f),
			    FoodEntity("소 가공(기타), 우족국물(우족 26g/물 100ml) ",2f),
			    FoodEntity("소 가공(기타), 육포 ",361f),
			    FoodEntity("소 가공(기타), 잡뼈국물(한우) ",28f),
			    FoodEntity("소 부산물, 간, 삶은것 ",191f),
			    FoodEntity("소 부산물, 허파, 삶은것 ",120f),
			    FoodEntity("소고기, 수입산, 갈비, 구운것 ",400f),
			    FoodEntity("소고기, 수입산, 목심, 삶은것 ",359f),
			    FoodEntity("소고기, 수입산, 설도, 구운것 ",164f),
			    FoodEntity("소고기, 수입산, 안심, 구운것 ",267f),
			    FoodEntity("소고기, 수입산, 양지, 삶은것 ",121.8f),
			    FoodEntity("소고기, 수입산, 채끝, 구운것 ",138f),
			    FoodEntity("소시지,쇠고기소시지",109.2f),
			    FoodEntity("송아지 부산물, 간, 삶은것 ",193f),
			    FoodEntity("송아지 부산물, 골, 삶은것 ",136f),
			    FoodEntity("송아지 부산물, 신장, 삶은것 ",164f),
			    FoodEntity("송아지 부산물, 심장, 삶은것 ",186f),
			    FoodEntity("송아지 부산물, 허파, 삶은것 ",103f),
			    FoodEntity("송아지 부산물, 혀, 삶은것 ",202f),
			    FoodEntity("송아지고기, 갈비, 구운것 ",229f),
			    FoodEntity("송아지고기, 갈비, 삶은것 ",251f),
			    FoodEntity("송아지고기, 등심, 구운것 ",217f),
			    FoodEntity("송아지고기, 등심, 삶은것 ",284f),
			    FoodEntity("송아지고기, 살코기, 삶은것 ",188f),
			    FoodEntity("송아지고기, 설도, 볶은것 ",212f),
			    FoodEntity("송아지고기, 설도, 삶은것 ",126.6f),
			    FoodEntity("송아지고기, 어깨, 구운것 ",184f),
			    FoodEntity("송아지고기, 어깨, 삶은것 ",235f),
			    FoodEntity("송아지고기, 채끝, 구운것 ",202f),
			    FoodEntity("송아지고기, 채끝, 삶은것 ",252f),
			    FoodEntity("쇠뼈국물,사골국물, 옛날사골곰탕(오뚜기)",44f),
			    FoodEntity("스튜, 레토르트 ",118f),
			    FoodEntity("스튜, 크림, 레토르트  ",119f),
			    FoodEntity("스튜,레토르트, 비프스튜(오뚜기)",385f),
			    FoodEntity("스튜,레토르트, 크림스튜(오뚜기)",490f),
			    FoodEntity("스튜,통조림",118f),
			    FoodEntity("어린양 부산물, 간, 삶은것 ",220f),
			    FoodEntity("어린양고기, 갈비, 구운것 ",359f),
			    FoodEntity("어린양고기, 다리, 구운것 ",225f),
			    FoodEntity("어린양고기, 어깨, 구운것 ",276f),
			    FoodEntity("어린양고기, 어깨, 삶은것 ",278f),
			    FoodEntity("완자,완자, 3분미트볼(오뚜기)",200f),
			    FoodEntity("칠면조고기, 구운것 ",170f),
			    FoodEntity("햄버거스테이크,햄버거스테이크, 3분햄버그스테이크(오뚜기)",180f),
			    FoodEntity("거위알, 삶은것 ",187f),
			    FoodEntity("기러기알, 삶은것 ",212f),
			    FoodEntity("달걀 가공(기타), 달걀부침(후라이) ",187f),
			    FoodEntity("달걀 가공(기타), 수란 ",164f),
			    FoodEntity("달걀 가공(기타), 스크램블드에그 ",149f),
			    FoodEntity("달걀, 삶은것 ",146f),
			    FoodEntity("메추라기알, 삶은것 ",175f),
			    FoodEntity("오리알 가공(기타), 피단 ",175f),
			    FoodEntity("가다랑어 가공(기타), 내장젓 ",78f),
			    FoodEntity("가다랑어 가공(기타), 육수 ",0f),
			    FoodEntity("가다랑어 가공(통조림), 통조림 ",145f),
			    FoodEntity("가다랑어, 반건 ",55.8f),
			    FoodEntity("가다랑어, 튀긴것 ",392f),
			    FoodEntity("가다랭이,건조",54.45f),
			    FoodEntity("가리비 가공(통조림), 통조림 ",112f),
			    FoodEntity("가리비, 관자, 자건",322f),
			    FoodEntity("가리비, 삶은것 ",100f),
			    FoodEntity("가리비, 튀긴것 ",215f),
			    FoodEntity("가오리 가공(기타), 조미건품 ",319f),
			    FoodEntity("가자미, 구운것 ",144f),
			    FoodEntity("가자미, 삶은것 ",114f),
			    FoodEntity("갈치 가공(기타), 얼간품 ",188f),
			    FoodEntity("갈치 가공(기타), 젓 ",184f),
			    FoodEntity("강달이,강달이",110f),
			    FoodEntity("갯가재, 삶은것 ",93f),
			    FoodEntity("검복 가공(기타), 조미건품",295f),
			    FoodEntity("게르치, 삶은것 ",173f),
			    FoodEntity("게살,자건품",45.3f),
			    FoodEntity("게알젓,게알젓",241f),
			    FoodEntity("고둥,매끈이고둥, 삶은것",275f),
			    FoodEntity("고등어 가공(기타), 자반고등어 ",172f),
			    FoodEntity("고등어 가공(통조림), 통조림 ",160f),
			    FoodEntity("고등어, 구운것 ",271f),
			    FoodEntity("고등어, 반건 ",348f),
			    FoodEntity("고등어, 삶은것 ",253f),
			    FoodEntity("굴 가공(기타), 어리굴젓 ",95f),
			    FoodEntity("굴 가공(기타), 튀김, 튀김옷 ",199f),
			    FoodEntity("굴 가공(통조림), 통조림 ",87f),
			    FoodEntity("굴 가공(통조림), 훈제통조림 ",311f),
			    FoodEntity("까나리, 자건 ",245f),
			    FoodEntity("꼴뚜기 가공(기타), 양념젓",111f),
			    FoodEntity("꼴뚜기 가공(기타), 젓 ",88f),
			    FoodEntity("꼴뚜기, 자건",286f),
			    FoodEntity("꽁치 가공(기타), 염장품 ",178f),
			    FoodEntity("꽁치 가공(통조림), 통조림 ",229f),
			    FoodEntity("꽁치, 구운것 ",299f),
			    FoodEntity("꽃게, 찐것 ",83f),
			    FoodEntity("꽃새우 가공(기타), 새우튀김, 튀김옷",242f),
			    FoodEntity("꽃새우 가공(기타), 장조림 ",240f),
			    FoodEntity("꽃새우 가공(기타), 젓 ",4.02f),
			    FoodEntity("꽃새우, 자건",307f),
			    FoodEntity("꽃새우, 찐것 ",118f),
			    FoodEntity("날치 가공(기타), 염장품 ",124f),
			    FoodEntity("농어, 구운것 ",124f),
			    FoodEntity("눈강달이 가공(기타), 젓 ",107f),
			    FoodEntity("눈퉁멸 가공(기타), 포 ",344f),
			    FoodEntity("닭게 가공(기타), 젓 ",60f),
			    FoodEntity("닭게, 삶은것 ",73f),
			    FoodEntity("대게 가공(통조림), 통조림, 영덕",73f),
			    FoodEntity("대게, 삶은것, 영덕",69f),
			    FoodEntity("대게, 자건 ",314f),
			    FoodEntity("대구 가공(기타), 대구포",312f),
			    FoodEntity("대구 가공(기타), 반건, 염장품 ",201f),
			    FoodEntity("대구 가공(기타), 아가미젓 ",76f),
			    FoodEntity("대구 가공(기타), 염장품 ",91f),
			    FoodEntity("대구 가공(기타), 젓 ",66f),
			    FoodEntity("대구, 구운것 ",109f),
			    FoodEntity("도루묵 가공(기타), 염건품 ",282f),
			    FoodEntity("둑중개 가공(기타), 조림 ",302f),
			    FoodEntity("둑중개, 삶은것 ",122f),
			    FoodEntity("말쥐치 가공(기타), 조미건품 ",325f),
			    FoodEntity("매끈이고둥 가공(통조림), 통조림 ",25.8f),
			    FoodEntity("멸치 가공(기타), 액젓 ",29f),
			    FoodEntity("멸치 가공(기타), 육수 ",0f),
			    FoodEntity("멸치 가공(기타), 젓 ",167f),
			    FoodEntity("멸치 가공(통조림), 유지통조림 ",178f),
			    FoodEntity("멸치, 대멸치, 자건 ",303f),
			    FoodEntity("멸치, 잔멸치, 자건 ",239f),
			    FoodEntity("멸치, 중멸치, 자건 ",232f),
			    FoodEntity("명태 가공(기타), 명란젓 ",126f),
			    FoodEntity("명태 가공(기타), 조미포",319f),
			    FoodEntity("명태 가공(기타), 창란젓 ",118f),
			    FoodEntity("명태 가공(기타), 코다리 ",108f),
			    FoodEntity("명태 가공(기타), 코다리, 구운것 ",111f),
			    FoodEntity("명태 가공(기타), 포 ",372f),
			    FoodEntity("명태 가공(기타), 황태포",349f),
			    FoodEntity("명태, 구운것 ",110f),
			    FoodEntity("무지개송어, 구운것 ",150f),
			    FoodEntity("문어, 삶은것 ",99f),
			    FoodEntity("문절망둑 가공(기타), 당조림 ",84.3f),
			    FoodEntity("문절망둑 가공(기타), 장조림 ",258f),
			    FoodEntity("미꾸리, 삶은것 ",83f),
			    FoodEntity("민어 가공(기타), 알, 염장품 ",298f),
			    FoodEntity("민어 가공(기타), 조미건품(암치) ",327f),
			    FoodEntity("민어 가공(기타), 튀김, 튀김옷 ",221f),
			    FoodEntity("민어, 구운것 ",106f),
			    FoodEntity("바가사리,바가사리",146f),
			    FoodEntity("바다빙어, 구운것 ",124f),
			    FoodEntity("바닷가재, 찐것 ",83f),
			    FoodEntity("바지락 가공(기타), 장조림 ",244f),
			    FoodEntity("바지락 가공(기타), 젓 ",51f),
			    FoodEntity("바지락 가공(통조림), 통조림 ",95f),
			    FoodEntity("박대, 반건 ",104f),
			    FoodEntity("방어 가공(통조림), 훈제통조림 ",328f),
			    FoodEntity("방어, 구운것 ",304f),
			    FoodEntity("백합(대합) 가공(통조림), 조미통조림 ",128f),
			    FoodEntity("백합(대합), 구운것 ",77f),
			    FoodEntity("백합(대합), 삶은것 ",87f),
			    FoodEntity("백합,건조",350f),
			    FoodEntity("밴댕이 가공(기타), 젓 ",115f),
			    FoodEntity("밴댕이, 자건 ",302f),
			    FoodEntity("뱀장어, 구운것 ",241f),
			    FoodEntity("뱅어 가공(기타), 뱅어포",362f),
			    FoodEntity("보라성게 가공(기타), 알젓 ",150f),
			    FoodEntity("보리새우, 삶은것, 양식 ",124f),
			    FoodEntity("보말고둥 가공(통조림), 조미통조림",29.7f),
			    FoodEntity("보말고둥, 구운것 ",99f),
			    FoodEntity("보말고둥, 삶은것 ",106f),
			    FoodEntity("볼락, 구운것 ",109f),
			    FoodEntity("볼락,불볼락",125f),
			    FoodEntity("불동꼴뚜기 가공(기타), 조림 ",260f),
			    FoodEntity("불동꼴뚜기 가공(기타), 훈제조미 ",325f),
			    FoodEntity("불동꼴뚜기, 삶은것 ",104f),
			    FoodEntity("붕어, 구운것 ",177f),
			    FoodEntity("붕어, 삶은것 ",225f),
			    FoodEntity("붕장어 가공(기타), 뼈튀김 ",579f),
			    FoodEntity("빙어 가공(기타), 당조림 ",87.3f),
			    FoodEntity("빙어 가공(기타), 장조림 ",272f),
			    FoodEntity("빙어, 자건 ",189f),
			    FoodEntity("삼치 가공(기타), 젓 ",106f),
			    FoodEntity("삼치, 구운것 ",202f),
			    FoodEntity("새우 가공(기타), 육젓 ",43f),
			    FoodEntity("새우 가공(기타), 추젓 ",49f),
			    FoodEntity("새우 가공(기타), 토굴대때기젓 ",55f),
			    FoodEntity("새우 가공(기타), 토굴동백하젓 ",51f),
			    FoodEntity("새우 가공(기타), 토굴오젓 ",60f),
			    FoodEntity("새우 가공(기타), 토굴육젓 ",59f),
			    FoodEntity("새우 가공(기타), 토굴추젓 ",48f),
			    FoodEntity("새조개 가공(기타), 조미건품 ",315f),
			    FoodEntity("성게 가공(기타), 알젓 ",105f),
			    FoodEntity("성게 가공(기타), 젓 ",135f),
			    FoodEntity("성게 가공(통조림), 통조림 ",144f),
			    FoodEntity("소라 가공(통조림), 통조림 ",128f),
			    FoodEntity("송어 가공(기타), 염장품 ",234f),
			    FoodEntity("송어 가공(기타), 젓 ",164f),
			    FoodEntity("송어 가공(통조림), 통조림 ",160f),
			    FoodEntity("숭어 가공(기타), 알염건품",444f),
			    FoodEntity("숭어, 구운것 ",150f),
			    FoodEntity("시바새우(중하) 가공(기타), 젓 ",92f),
			    FoodEntity("시바새우(중하) 가공(기타), 조미건품 ",331f),
			    FoodEntity("시바새우(중하) 가공(통조림), 통조림 ",100f),
			    FoodEntity("시바새우(중하), 자건 ",300f),
			    FoodEntity("아가미젓,아가미젓",80f),
			    FoodEntity("아미 가공(기타), 젓 ",57f),
			    FoodEntity("아미 가공(기타), 조림 ",63.3f),
			    FoodEntity("애꼬치, 구운것 ",145f),
			    FoodEntity("어단,어단",133f),
			    FoodEntity("어란젓,어란젓",234f),
			    FoodEntity("연어 가공(기타), 알염장품",257f),
			    FoodEntity("연어 가공(기타), 연어다시마조림",126.3f),
			    FoodEntity("연어 가공(기타), 염장품 ",147f),
			    FoodEntity("연어 가공(기타), 젓 ",143f),
			    FoodEntity("연어 가공(기타), 찌기절임",39.25f),
			    FoodEntity("연어 가공(기타), 훈제 ",171f),
			    FoodEntity("연어 가공(통조림), 통조림 ",136f),
			    FoodEntity("오징어 가공(기타), 내장젓 ",102f),
			    FoodEntity("오징어 가공(기타), 당조림 ",298f),
			    FoodEntity("오징어 가공(기타), 양념젓",128f),
			    FoodEntity("오징어 가공(기타), 젓 ",77f),
			    FoodEntity("오징어 가공(기타), 조미구이 ",308f),
			    FoodEntity("오징어 가공(기타), 조미포 ",295f),
			    FoodEntity("오징어 가공(기타), 훈제조미품",215f),
			    FoodEntity("오징어, 구운것 ",117f),
			    FoodEntity("오징어, 삶은것 ",103f),
			    FoodEntity("오징어, 튀긴것 ",175f),
			    FoodEntity("오징어,훈제품",244f),
			    FoodEntity("옥돔, 구운것 ",119f),
			    FoodEntity("옥돔, 반건 ",104f),
			    FoodEntity("옥돔, 삶은것 ",125f),
			    FoodEntity("왕게 가공(통조림), 통조림 ",27.6f),
			    FoodEntity("왕게, 삶은것 ",80f),
			    FoodEntity("은어 가공(기타), 내장젓 ",131f),
			    FoodEntity("은어 가공(기타), 당조림 ",88.5f),
			    FoodEntity("은어 부산물, 내장, 구운것 ",194f),
			    FoodEntity("은어, 구운것 ",177f),
			    FoodEntity("임연수어 가공(기타), 염장품 ",198f),
			    FoodEntity("임연수어, 반건 ",142f),
			    FoodEntity("잉어, 삶은것 ",208f),
			    FoodEntity("장문볼락, 구운것 ",96f),
			    FoodEntity("전갱이 가공(기타), 염건품 ",262f),
			    FoodEntity("전갱이 가공(기타), 조미반건품",168f),
			    FoodEntity("전갱이 가공(기타), 조미반건품, 구운것 ",220f),
			    FoodEntity("전갱이 가공(기타), 조미통조림 ",137f),
			    FoodEntity("전갱이, 구운것 ",164f),
			    FoodEntity("전갱이, 삶은것 ",143f),
			    FoodEntity("전복 가공(기타), 젓 ",101f),
			    FoodEntity("전복 가공(통조림), 조미통조림 ",137f),
			    FoodEntity("전복 가공(통조림), 통조림, 삶은것 ",101f),
			    FoodEntity("전복, 튀긴것 ",190f),
			    FoodEntity("전어 가공(기타), 젓 ",130f),
			    FoodEntity("전어 가공(기타), 피클 ",50f),
			    FoodEntity("점줄우럭, 구운것 ",118f),
			    FoodEntity("젓새우 가공(기타), 백하젓 ",55f),
			    FoodEntity("젓새우 가공(기타), 조림 ",244f),
			    FoodEntity("정어리 가공(기타), 염건품 ",188f),
			    FoodEntity("정어리 가공(기타), 염장품 ",153f),
			    FoodEntity("정어리 가공(통조림), 조미통조림 ",125f),
			    FoodEntity("정어리 가공(통조림), 토마토통조림 ",151f),
			    FoodEntity("정어리 가공(통조림), 통조림 ",128f),
			    FoodEntity("정어리, 구운것 ",244f),
			    FoodEntity("정어리, 삶은것 ",224f),
			    FoodEntity("정어리, 자건 ",113f),
			    FoodEntity("조기(참조기) 가공(기타), 굴비 ",332f),
			    FoodEntity("조기(참조기) 가공(기타), 젓 ",81f),
			    FoodEntity("쥐치 가공(기타), 포",339f),
			    FoodEntity("진주담치, 구운것  ",173f),
			    FoodEntity("참다랑어 가공(기타), 샐러드 ",189f),
			    FoodEntity("참다랑어 가공(통조림), 유지통조림 ",297f),
			    FoodEntity("참다랑어, 구운것 ",185f),
			    FoodEntity("참돔, 구운것 ",226f),
			    FoodEntity("참돔, 삶은것 ",226f),
			    FoodEntity("청어 가공(기타), 알염장품 ",94f),
			    FoodEntity("청어 가공(기타), 염장품 ",159f),
			    FoodEntity("청어 가공(기타), 훈제 ",305f),
			    FoodEntity("청어, 자건 ",123f),
			    FoodEntity("크릴 가공(기타), 즙 ",82f),
			    FoodEntity("크릴 가공(기타), 페이스트 ",130f),
			    FoodEntity("크릴, 삶은것 ",86f),
			    FoodEntity("피조개 가공(통조림), 조미통조림 ",120f),
			    FoodEntity("학공치 가공(기타), 조미건품 ",341f),
			    FoodEntity("해삼 가공(기타), 내장젓 ",45f),
			    FoodEntity("해삼 가공(기타), 염장품 ",35f),
			    FoodEntity("해삼 가공(기타), 젓 ",33f),
			    FoodEntity("해파리,염장품",8.75f),
			    FoodEntity("해파리젓,해파리젓",33f),
			    FoodEntity("홍연어 가공(기타), 훈제 ",161f),
			    FoodEntity("홍연어, 구운것 ",177f),
			    FoodEntity("홍합(참담치) 가공(통조림), 통조림 ",94f),
			    FoodEntity("홍합(참담치), 자건",391f),
			    FoodEntity("황다랑어 가공(통조림), 통조림 ",33.6f),
			    FoodEntity("황새치 가공(기타), 젓 ",123f),
			    FoodEntity("황새치, 구운것 ",174f),
			    FoodEntity("김 가공(기타), 맛김, 마른것 ",172f),
			    FoodEntity("김 가공(기타), 조림 ",0.74f),
			    FoodEntity("김, 조선김, 마른것 ",121f),
			    FoodEntity("김, 참김, 구운것 ",174f),
			    FoodEntity("다시마 가공(기타), 다시마말이 ",0.74f),
			    FoodEntity("다시마 가공(기타), 염장품 ",16f),
			    FoodEntity("다시마 가공(기타), 육수 ",1f),
			    FoodEntity("다시마 가공(기타), 튀각 ",199f),
			    FoodEntity("다시마, 조림 ",51f),
			    FoodEntity("모자반 가공(기타), 염장품 ",18f),
			    FoodEntity("미역 가공(기타), 염장품 ",34f),
			    FoodEntity("미역 가공(기타), 염장품, 데친것 ",35f),
			    FoodEntity("미역 가공(기타), 튀각 ",294f),
			    FoodEntity("미역 줄기 가공(기타), 염장품, 삶은것, 탈염 ",15f),
			    FoodEntity("미역 줄기, 삶은것",4.5f),
			    FoodEntity("우뭇가사리 가공(기타), 한천 ",154f),
			    FoodEntity("우뭇가사리 가공(면류), 우무(묵)",2f),
			    FoodEntity("톳, 자건 ",135f),
			    FoodEntity("모유 ",65f),
			    FoodEntity("분유, 1단계 ",516f),
			    FoodEntity("분유, 2단계 ",353f),
			    FoodEntity("분유, 3단계 ",490f),
			    FoodEntity("분유, 전지 ",504f),
			    FoodEntity("분유, 탈지 ",359f),
			    FoodEntity("산양유 ",63f),
			    FoodEntity("샤베트 ",127f),
			    FoodEntity("아이스밀크 ",167f),
			    FoodEntity("아이스크림(유지방 12%) ",212f),
			    FoodEntity("아이스크림, 딸기맛 ",192f),
			    FoodEntity("아이스크림, 바닐라맛 ",186f),
			    FoodEntity("아이스크림, 소프트 바닐라맛 ",207f),
			    FoodEntity("아이스크림, 초콜렛맛 ",215f),
			    FoodEntity("연유, 가당 ",327f),
			    FoodEntity("연유, 무가당 ",135f),
			    FoodEntity("연유, 탈지 ",27.5f),
			    FoodEntity("요구르트, 액상 ",65f),
			    FoodEntity("요구르트, 호상, 딸기맛 ",101f),
			    FoodEntity("요구르트, 호상, 우유, 무가당 ",56f),
			    FoodEntity("요구르트, 호상, 탈지, 가당 ",96f),
			    FoodEntity("우유 ",61f),
			    FoodEntity("우유, 고지방 ",146f),
			    FoodEntity("우유, 고칼슘 ",53f),
			    FoodEntity("우유, 딸기맛 ",58f),
			    FoodEntity("우유, 바나나맛 ",77f),
			    FoodEntity("우유, 저지방 ",36f),
			    FoodEntity("우유, 초코맛 ",63f),
			    FoodEntity("우유, 커피맛 ",63f),
			    FoodEntity("우유, 탈지 ",66f),
			    FoodEntity("치즈, 가공치즈 ",64f),
			    FoodEntity("치즈, 모짜렐라 ",215f),
			    FoodEntity("치즈, 자연치즈 ",65.2f),
			    FoodEntity("치즈, 체다 ",236f),
			    FoodEntity("치즈, 카테지 ",105f),
			    FoodEntity("치즈, 크림 ",342f),
			    FoodEntity("치즈, 파마산, 일반용",432f),
			    FoodEntity("치즈,치즈",67f),
			    FoodEntity("크림(유지방 38%) ",380f),
			    FoodEntity("크림, 휘핑 ",399f),
			    FoodEntity("닭기름 ",900f),
			    FoodEntity("돼지기름 ",941f),
			    FoodEntity("들기름 ",921f),
			    FoodEntity("땅콩기름 ",884f),
			    FoodEntity("땅콩버터 ",642f),
			    FoodEntity("마가린 ",721f),
			    FoodEntity("버터 ",778f),
			    FoodEntity("생선기름,생선기름",941f),
			    FoodEntity("쇠기름(우지)",940f),
			    FoodEntity("쇼트닝 ",941f),
			    FoodEntity("쌀겨기름(미강유)",921f),
			    FoodEntity("양기름 ",902f),
			    FoodEntity("연어기름 ",902f),
			    FoodEntity("옥수수기름 ",921f),
			    FoodEntity("올리브유 ",921f),
			    FoodEntity("참기름 ",915f),
			    FoodEntity("커피크리머, 액상, 식물성지방 ",248f),
			    FoodEntity("코코넛유 ",921f),
			    FoodEntity("콩기름 ",921f),
			    FoodEntity("팜유 ",921f),
			    FoodEntity("해바라기유 ",921f),
			    FoodEntity("혼합식물성유 ",921f),
			    FoodEntity("과일탄산음료,과일탄산음료",98f),
			    FoodEntity("구절초차 ",345f),
			    FoodEntity("국화차 ",358f),
			    FoodEntity("녹차, 잎, 보성 ",371f),
			    FoodEntity("녹차, 침출액 ",1f),
			    FoodEntity("다래나무순차, 침출액 ",1f),
			    FoodEntity("대추차, 침출액  ",41f),
			    FoodEntity("도라지차, 침출액  ",22f),
			    FoodEntity("돌복숭아주(알코올 13%) ",127f),
			    FoodEntity("둥글레차, 침출액 ",2f),
			    FoodEntity("드라이진(알코올 47%) ",284f),
			    FoodEntity("럼(알코올 40%) ",240f),
			    FoodEntity("레몬에이드 ",14f),
			    FoodEntity("마늘음료,마늘음료, 마늘쑥음료",196f),
			    FoodEntity("마늘음료,마늘음료, 마늘호박음료",150f),
			    FoodEntity("막걸리(알코올 6%) ",56f),
			    FoodEntity("매실주(알코올 13%) ",156f),
			    FoodEntity("맥주(알코올 4.5%) ",12f),
			    FoodEntity("맥주, 흑맥주(알코올 4.2%) ",46f),
			    FoodEntity("맥주,생맥주",131.35f),
			    FoodEntity("맥주,합성맥주",131.35f),
			    FoodEntity("보드카,보드카, 알콜50%",295f),
			    FoodEntity("보리차, 침출액 ",1f),
			    FoodEntity("브랜디(알코올 40%) ",237f),
			    FoodEntity("사과차, 침출액 ",167f),
			    FoodEntity("산채발효음료,산채발효음료",198f),
			    FoodEntity("생강음료,생강음료",106f),
			    FoodEntity("샴페인(알코올 6%) ",45f),
			    FoodEntity("쉐이크, 딸기맛 ",113f),
			    FoodEntity("쉐이크, 바닐라맛 ",148f),
			    FoodEntity("쉐이크, 초콜렛맛 ",127f),
			    FoodEntity("식혜, 캔 ",41f),
			    FoodEntity("쌀음료",54f),
			    FoodEntity("쑥차 ",338f),
			    FoodEntity("알로에음료,알로에음료",50f),
			    FoodEntity("야콘차, 침출액 ",98f),
			    FoodEntity("오가피주(알코올 13%) ",107f),
			    FoodEntity("오미자차 ",371f),
			    FoodEntity("옥수수차,옥수수차",762f),
			    FoodEntity("우롱차, 침출액 ",0f),
			    FoodEntity("우롱차, 캔 ",0f),
			    FoodEntity("우롱차,분말",256f),
			    FoodEntity("위스키(알코올 40%) ",237f),
			    FoodEntity("유자차",251f),
			    FoodEntity("이온음료 ",24f),
			    FoodEntity("인삼차, 과립 ",394f),
			    FoodEntity("장군차 ",361f),
			    FoodEntity("진,진, 알콜37%",213f),
			    FoodEntity("청주(알코올 16%) ",133f),
			    FoodEntity("치커리차",369f),
			    FoodEntity("칠보식,칠보식",361f),
			    FoodEntity("칵테일, 데이커리 ",61f),
			    FoodEntity("칵테일, 데킬라썬라이즈 ",123f),
			    FoodEntity("칵테일, 마티니(알코올 32%) ",223f),
			    FoodEntity("칵테일, 버번앤소다 ",105f),
			    FoodEntity("칵테일, 블러드메리 ",17f),
			    FoodEntity("칵테일, 스크류드라이버(알코올 6.6%) ",83f),
			    FoodEntity("칵테일, 위스키사우어(알코올 16.8%)  ",119f),
			    FoodEntity("칵테일, 진토닉(알코올 7.1%) ",78f),
			    FoodEntity("칵테일, 페퍼민트(알코올 20%) ",302f),
			    FoodEntity("칵테일, 피나콜라다(알코올 9.9%)  ",180f),
			    FoodEntity("칵테일,맨하탄",225f),
			    FoodEntity("커피, 원두 ",431f),
			    FoodEntity("커피, 원두여과액 ",4f),
			    FoodEntity("커피, 캔 ",26f),
			    FoodEntity("커피, 커피믹스액(커피믹스 12g)",48f),
			    FoodEntity("커피, 커피액 ",4f),
			    FoodEntity("커피,레귤라커피",584f),
			    FoodEntity("커피,커피음료",6f),
			    FoodEntity("콜라,일반콜라, 체리콜라",102.5f),
			    FoodEntity("탄산음료, 사이다 ",39f),
			    FoodEntity("탄산음료, 소다수 ",0f),
			    FoodEntity("탄산음료, 저칼로리콜라 ",1f),
			    FoodEntity("탄산음료, 콜라 ",47f),
			    FoodEntity("토닉워터 ",34f),
			    FoodEntity("포도주, 백포도주(알코올 12%) ",74f),
			    FoodEntity("포도주, 적포도주(알코올 12%) ",70f),
			    FoodEntity("포도주,단포도주",79.95f),
			    FoodEntity("현미녹차,차잎과현미",305f),
			    FoodEntity("홍차, 침출액 ",3f),
			    FoodEntity("홍차, 침출액, 레몬맛  ",33f),
			    FoodEntity("홍차, 캔음료 ",30f),
			    FoodEntity("홍차, 티백 ",311f),
			    FoodEntity("고추냉이(와사비), 페이스트 ",285f),
			    FoodEntity("나토(일본식 청국장)",200f),
			    FoodEntity("된장 ",131f),
			    FoodEntity("된장, 보리된장 ",164f),
			    FoodEntity("된장, 일본식",217f),
			    FoodEntity("된장, 재래된장 ",161f),
			    FoodEntity("된장,개량식(양조된장)",131f),
			    FoodEntity("마요네즈, 난황 ",702f),
			    FoodEntity("샐러드드레싱, 사우전드아일랜드 ",472f),
			    FoodEntity("샐러드드레싱, 이탈리안 ",291f),
			    FoodEntity("샐러드드레싱, 프렌치 ",457f),
			    FoodEntity("스파게티, 병조림 ",61f),
			    FoodEntity("식초, 감(아세트산 5.5%) ",14f),
			    FoodEntity("식초, 배 ",43f),
			    FoodEntity("식초, 사과(아세트산 5.0%) ",11f),
			    FoodEntity("식초, 쌀(아세트산 4.5%) ",30f),
			    FoodEntity("식초, 알로에 ",12f),
			    FoodEntity("식초, 양조 ",11f),
			    FoodEntity("식초, 포도(아세트산 4.8%) ",5f),
			    FoodEntity("식초, 현미(아세트산 5.0%)",19f),
			    FoodEntity("식초,식초",30f),
			    FoodEntity("쌈장 ",200f),
			    FoodEntity("쌈장(혼합장),쌈장(혼합장)",171f),
			    FoodEntity("육두구 ",559f),
			    FoodEntity("청국장 ",108f),
			    FoodEntity("카레, 레토르트 ",111f),
			    FoodEntity("카레,레토르트, 3분야채카레(오뚜기)",166f),
			    FoodEntity("카레,레토르트, 3분치킨카레(오뚜기)",176f),
			    FoodEntity("카레,레토르트, 바몬드카레(오뚜기)",740f),
			    FoodEntity("카레,레토르트, 인도카레(오뚜기)",880f),
			    FoodEntity("카레,레토르트, 카레(오뚜기)",770f),
			    FoodEntity("카레,통조림",236f),
			    FoodEntity("템페 ",193f),
			    FoodEntity("토마토케첩 ",121f),
			    FoodEntity("김말이튀김, 튀긴것 ",251f),
			    FoodEntity("김치, 열무물김치 ",10f),
			    FoodEntity("김치, 유채물김치 ",17f),
			    FoodEntity("만두, 군만두, 튀긴것 ",274f),
			    FoodEntity("새우튀김 ",301f),
			    FoodEntity("샐러드류,치킨샐러드",120f),
			    FoodEntity("스파게티, 전자렌지용 ",1010.8f),
			    FoodEntity("아귀찜",320f),
			    FoodEntity("오징어튀김 ",308f),
			    FoodEntity("인스턴트 국류,북어국, 북어국(오뚜기)",325f),
			    FoodEntity("채소튀김",321f),
			    FoodEntity("치킨, 패스트푸드, 너겟, 튀긴것 ",280f),
			    FoodEntity("치킨, 패스트푸드, 버팔로윙, 튀긴것 ",204f),
			    FoodEntity("치킨, 패스트푸드, 텐더, 튀긴것 ",288f),
			    FoodEntity("치킨, 패스트푸드, 핫윙, 튀긴것 ",359f),
			    FoodEntity("고로쇠나무수액 ",7f),
			    FoodEntity("녹용, 중대 ",271f),
			    FoodEntity("달팽이 가공(통조림), 통조림 ",82f),
			    FoodEntity("대나무추출액 ",2f),
			    FoodEntity("번데기, 통조림 ",99f),
			    FoodEntity("솔잎추출액 ",9f),
			    FoodEntity("수세미, 수액 ",6f),
			    FoodEntity("인삼 가공(기타), 홍삼추출액 ",213f),
			    FoodEntity("참나무, 수액 ",0f),
			    FoodEntity("프로폴리스 ",642f),
			    FoodEntity("단감",51f),
			    FoodEntity("연시",57f),
			    FoodEntity("구아바",38f),
			    FoodEntity("밀감",40f),
			    FoodEntity("한라봉",51f),
			    FoodEntity("금귤",81f),
			    FoodEntity("다래",67f),
			    FoodEntity("대추",90f),
			    FoodEntity("두리안",133f),
			    FoodEntity("딸기",36f),
			    FoodEntity("라임",30f),
			    FoodEntity("레몬",30f),
			    FoodEntity("롱간스",59f),
			    FoodEntity("리치",63f),
			    FoodEntity("망고",64f),
			    FoodEntity("애플망고",49f),
			    FoodEntity("머루 포도",62f),
			    FoodEntity("머스크 렐론",36f),
			    FoodEntity("화이트 멜론",36f),
			    FoodEntity("모과",78f),
			    FoodEntity("무화과",54f),
			    FoodEntity("바나나",80f),
			    FoodEntity("배",48f),
			    FoodEntity("버찌",60f),
			    FoodEntity("복분자",60f),
			    FoodEntity("백도 복숭아",36f),
			    FoodEntity("천도 복숭아",41f),
			    FoodEntity("황도 복숭아",45f),
			    FoodEntity("블랙베리",49f),
			    FoodEntity("블루베리",57f),
			    FoodEntity("비파",46f),
			    FoodEntity("사과",49f),
			    FoodEntity("산딸기",32f),
			    FoodEntity("산수유",292f),
			    FoodEntity("살구",30f),
			    FoodEntity("석류",56f),
			    FoodEntity("소귀나무열매",24f),
			    FoodEntity("수박",31f),
			    FoodEntity("아떼모야",73f),
			    FoodEntity("아보카도",187f),
			    FoodEntity("아세로라",36f),
			    FoodEntity("앵두",61f),
			    FoodEntity("엘더베리",73f),
			    FoodEntity("오디",49f),
			    FoodEntity("오렌지",44f),
			    FoodEntity("용과",45f),
			    FoodEntity("유자",42f),
			    FoodEntity("으름",158f),
			    FoodEntity("자두",26f),
			    FoodEntity("자몽",31f),
			    FoodEntity("참외",38f),
			    FoodEntity("칼슘나무열매",50f),
			    FoodEntity("코코넛",20f),
			    FoodEntity("크랜베리",46f),
			    FoodEntity("키위",64f),
			    FoodEntity("탱자",84f),
			    FoodEntity("파인애플",55f),
			    FoodEntity("파파야",38f),
			    FoodEntity("거봉",65f),
			    FoodEntity("캠벨얼리 포도",46f)
			    )
    }
}